version: "3"

tasks:
  build:
    cmds:
      - docker build . -t ghcr.io/sandbox-pokhara/nepal-ebilling-backend

  publish:
    cmds:
      - docker image push ghcr.io/sandbox-pokhara/nepal-ebilling-backend
